### ISSUE TITLE
Turtlebot2 Simulation

### ISSUE THREAD

**Issue by rmerriam** [gaunthan/Turtlebot2-On-Melodic#1]
Trying to run this in simulation. Gazebo runs and shows the Turtlebot and other objects. Running the 

 `roslaunch turtlebot_teleop keyboard_teleop.launch
`

doesn't cause any movement. I don't see any message when looking at 

`/cmd_vel_mux/input/teleop`

Any suggestions?

Also the `depthimage_to_laserscan ` nodelet doesn't load but I'm not concerned about it at the moment.

**Comment by Ircbarros** [comment]
Hi! Can you send your stdout showed in the terminal?

**Comment by gaunthan** [comment]
Hi. I think your problem may be caused by communication problem with rosmaster. 

Try use `roscore` to start a rosmaster in advance, and then bring up other nodes.

Otherwise, if you use `turtlebot_teleop` to start a rosmaster by default, and after that you restart the `turtlebot_teleop`, all communications created before will be broken. So `rostopic echo /cmd_vel_mux/input/teleop` won't prompt anything new!

**Comment by kris1025** [comment]
Does anyone know how to solve this problem?

**Comment by hlq1025** [comment]
> Hi! Can you send your stdout showed in the terminal?
Here are my stdout.
Control Your Turtlebot!
---------------------------
Moving around:
   u    i    o
   j    k    l
   m    ,    .

q/z : increase/decrease max speeds by 10%
w/x : increase/decrease only linear speed by 10%
e/c : increase/decrease only angular speed by 10%
space key, k : force stop
anything else : stop smoothly

CTRL-C to quit

currently:	speed 0.000398933268843	turn 0.00221629593802 
currently:	speed 0.000438826595727	turn 0.00243792553182 
currently:	speed 0.0004827092553	turn 0.002681718085 
currently:	speed 0.00043443832977	turn 0.0024135462765 
currently:	speed 0.000390994496793	turn 0.00217219164885 
currently:	speed 0.000351895047114	turn 0.00195497248396 
currently:	speed 0.000316705542402	turn 0.00175947523557 
currently:	speed 0.000285034988162	turn 0.00158352771201 
currently:	speed 0.000256531489346	turn 0.00142517494081 
currently:	speed 0.00028218463828	turn 0.00142517494081 
currently:	speed 0.000310403102108	turn 0.00142517494081 
currently:	speed 0.000279362791898	turn 0.00142517494081 
currently:	speed 0.000251426512708	turn 0.00142517494081 
currently:	speed 0.000226283861437	turn 0.00142517494081 
currently:	speed 0.000226283861437	turn 0.00156769243489

**Comment by hlq1025** [comment]
> Hi! Can you send your stdout showed in the terminal?




Here is my stdout.
Control Your Turtlebot!
---------------------------
Moving around:
   u    i    o
   j    k    l
   m    ,    .

q/z : increase/decrease max speeds by 10%
w/x : increase/decrease only linear speed by 10%
e/c : increase/decrease only angular speed by 10%
space key, k : force stop
anything else : stop smoothly

CTRL-C to quit

currently:	speed 2.28622885011e-05	turn 0.000127012713895 
currently:	speed 2.51485173512e-05	turn 0.000139713985284 
currently:	speed 2.76633690863e-05	turn 0.000153685383813 
currently:	speed 3.0429705995e-05	turn 0.000169053922194 
currently:	speed 3.34726765944e-05	turn 0.000185959314414 
currently:	speed 3.68199442539e-05	turn 0.000204555245855 
currently:	speed 4.05019386793e-05	turn 0.00022501077044 
currently:	speed 4.45521325472e-05	turn 0.000247511847484 
currently:	speed 4.90073458019e-05	turn 0.000272263032233 
currently:	speed 5.39080803821e-05	turn 0.000299489335456 
currently:	speed 5.92988884203e-05	turn 0.000329438269002 
currently:	speed 6.52287772624e-05	turn 0.000362382095902 
currently:	speed 7.17516549886e-05	turn 0.000398620305492 
currently:	speed 7.89268204875e-05	turn 0.000438482336041 
currently:	speed 8.68195025362e-05	turn 0.000482330569646

**Comment by hlq1025** [comment]
> Hi! Can you send your stdout showed in the terminal?
Here is my stdout.
Control Your Turtlebot!

Moving around:
   u    i    o
   j    k    l
   m    ,    .

q/z : increase/decrease max speeds by 10%
w/x : increase/decrease only linear speed by 10%
e/c : increase/decrease only angular speed by 10%
space key, k : force stop
anything else : stop smoothly

CTRL-C to quit

currently:	speed 4.92625116954e-05	turn 0.000246312558477 
currently:	speed 4.43362605258e-05	turn 0.000221681302629 
currently:	speed 3.99026344733e-05	turn 0.000199513172366 
currently:	speed 3.59123710259e-05	turn 0.00017956185513 
currently:	speed 3.23211339233e-05	turn 0.000161605669617 
currently:	speed 2.9089020531e-05	turn 0.000145445102655 
currently:	speed 2.61801184779e-05	turn 0.00013090059239 
currently:	speed 2.35621066301e-05	turn 0.000117810533151 
currently:	speed 2.59183172931e-05	turn 0.000117810533151 
currently:	speed 2.59183172931e-05	turn 0.000129591586466 
currently:	speed 2.33264855638e-05	turn 0.000116632427819 
currently:	speed 2.09938370074e-05	turn 0.000116632427819 
currently:	speed 1.88944533067e-05	turn 0.000116632427819 
currently:	speed 1.88944533067e-05	turn 0.000104969185037 
currently:	speed 2.07838986374e-05	turn 0.000115466103541

**Comment by kris1025** [comment]
> Hi! Can you send your stdout showed in the terminal?




Control Your Turtlebot!

Moving around:
   u    i    o
   j    k    l
   m    ,    .

q/z : increase/decrease max speeds by 10%
w/x : increase/decrease only linear speed by 10%
e/c : increase/decrease only angular speed by 10%
space key, k : force stop
anything else : stop smoothly

CTRL-C to quit

currently:	speed 0.000239264854169	turn 0.00119632427085 
currently:	speed 0.000215338368752	turn 0.00107669184376 
currently:	speed 0.000193804531877	turn 0.000969022659386 
currently:	speed 0.000174424078689	turn 0.000872120393447 
currently:	speed 0.00015698167082	turn 0.000784908354102 
currently:	speed 0.000141283503738	turn 0.000706417518692 
currently:	speed 0.000127155153365	turn 0.000635775766823 
currently:	speed 0.000114439638028	turn 0.000572198190141 
currently:	speed 0.000102995674225	turn 0.000514978371127 
currently:	speed 9.26961068028e-05	turn 0.000463480534014 
currently:	speed 8.34264961225e-05	turn 0.000417132480612 
currently:	speed 7.50838465102e-05	turn 0.000375419232551 
currently:	speed 6.75754618592e-05	turn 0.000337877309296 
currently:	speed 6.08179156733e-05	turn 0.000304089578366 
currently:	speed 5.4736124106e-05	turn 0.00027368062053

**Comment by kris1025** [comment]
I figured out this problem.follow the following tutorial ,then you  can use keyboard to control turtlebot.
https://www.ncnynl.com/archives/201904/2924.html.

**Comment by gaunthan** [comment]
Thanks! You may want to check out  https://github.com/gaunthan/Turtlebot2-On-Melodic/issues/2#issuecomment-562667082 and https://github.com/gaunthan/Turtlebot2-On-Melodic/issues/2#issuecomment-563581360
