### ISSUE TITLE
Minor: Specific Branch needed for kobuki

### ISSUE THREAD

**Issue by OAkyildiz** [gaunthan/Turtlebot2-On-Melodic#3]
The script needs an update as https://github.com/yujinrobot/kobuki needs [melodic](https://github.com/yujinrobot/kobuki/tree/melodic) branch to build without failing

**Comment by OAkyildiz** [comment]
Actually, ROS repository is only missing turtlebot2 packages for melodic.

Can use the following to get the dependencies
`sudo apt install ros-melodic-yocs-msgs ros-melodic-kobuki-{core,driver,dock-drive} ros-melodic-yujin-ocs`

**Comment by gaunthan** [comment]
Thanks. We have updated the branch of kobuki to melodic. See https://github.com/gaunthan/Turtlebot2-On-Melodic/pull/4
